#!/bin/bash

opkg install git

cd /tmp

git clone https://github.com/daniel00xE2/listakanalow.git
if [ $? -gt 0 ] ;then
echo "Błąd pobierania listy, koniec"
exit 1
else
echo "Lista pobrana"
fi

mv -f /tmp/listakanalow/blacklist /etc/enigma2/
mv -f /tmp/listakanalow/lamedb /etc/enigma2/
mv -f /tmp/listakanalow/bouquets.tv /etc/enigma2/
mv -f /tmp/listakanalow/bouquets.radio /etc/enigma2/
mv -f /tmp/listakanalow/userbouquet.polskie.tv /etc/enigma2/
if [ $? -gt 0 ] ;then
echo "Błąd instalacji listy, koniec"
exit 1
else
echo "Lista zainstalowana pomyślnie."
fi

rm -rf /tmp/listakanalow

echo "E2 jest restartowana..."

init 4
init 3
exit 0
